#!/bin/bash
#chmod a+rwx "./result/result_all.txt"
echo "=======myScript start======"
END=8

cat << EOF >./result/result_all.txt
file start
EOF
echo "$(date)" 1>> "./result/result_all.txt"
chmod a+rwx "./result/result_all.txt"
res_all="./result/result_all.txt"
echo "result path: $res_all"

for i in $(seq 1 $END);
do
  # file path
  res="./result/result$i.txt"
  input="./input/input0$i.c"  
 

  # save result into "result_all.txt"
  echo -e "\n\n=======================$input=========================" 1>>"${res_all}"
  echo "input:$input"                         1>>"${res_all}"
  echo "output:$res"                          1>>"${res_all}"
  echo "====================code===================================="    1>>"${res_all}"
  cat $input                                    1>>"${res_all}"
  echo "========================================================="         1>>"${res_all}"
  ./program $input                              1>>"${res_all}"
  echo -e "==================================================================\n\n"    1>>"${res_all}"

done

echo "=========myscript end==========="
